name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: ''

      - name: Upload static content
        uses: actions/upload-pages-artifact@v2
        with:
          path: './output'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
